### ISSUE TITLE
CompositeAlgorithm error

### ISSUE THREAD

**Issue by pwstokes225** [JuliaDiffEq/DelayDiffEq.jl#148] opened 2019-08-15 15:54 UTC
Specifying a `CompositeAlgorithm` currently results in the error:
```
ERROR: type FPFunctionalCache has no field caches
```
MWE:
```
using DelayDiffEq
prob = DDEProblem((du,u,h,p,t)->du[1]=-h(p,t-1)[1],[1.0],(p,t)->[1.0],(0.0,5.0))
choice_function(integrator) = 1
alg = CompositeAlgorithm((Tsit5(),RK4()),choice_function)
solve(prob,MethodOfSteps(alg))
```

**Comment by devmotion** [comment] 2019-08-15 19:02
Hej!

Thanks for your bug report. A bit unfortunate that this issue was not detected by our tests. The problem exists only in the in-place version, the example
```julia
using DelayDiffEq, Plots

prob = DDEProblem((u, h, p, t) -> -h(p, t - 1), 1.0, (p, t) -> 1.0, (0.0, 5.0))
choice_function(integrator) = 1
alg = CompositeAlgorithm((Tsit5(), RK4()), choice_function)
sol = solve(prob, MethodOfSteps(alg))

plot(sol)
```
works as expected.

The issue can be fixed easily by replacing
https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/9d3f538a24b115a10e58a80089ecc9292e75fee9/src/fpsolve/functional.jl#L123-L128
with
```julia
if iscomposite(alg)
  addsteps!(k, t, uprev, integrator.u, dt, f, p, integrator.cache.caches[integrator.cache.current],
            false, true, true)
else
  addsteps!(k, t, uprev, integrator.u, dt, f, p, integrator.cache, false, true, true)
end
```
i.e., it should be `integrator.cache` instead of `cache` (which refers to the cache of the fixed-point iteration).

Since the problem is already fixed by https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/147, I would actually prefer to merge that PR after adding an additional test for the issue you discovered. However, at the same time I would like someone else to have a look at the PR before it's merged. @ChrisRackauckas, do you think you'll have time to check the PR in the next days? Otherwise I'll push a quick fix :smiley:

**Comment by ChrisRackauckas** [comment] 2019-08-16 04:53
Fixed by https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/147 . We should get a release out soon.

**Closed by ChrisRackauckas** 2019-08-16 04:53 UTC

**Comment by devmotion** [comment] 2019-08-16 10:59
Release 5.14.0 which contains the fix is now available.
